# Generated by Django 5.1.4 on 2025-03-17 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='price_per_day',
            field=models.CharField(max_length=8),
        ),
    ]
